export interface PositionType {
    dhanClientId: string;
    tradingSymbol: string;
    securityId: string;
    positionType: 'LONG' | 'SHORT' | 'CLOSED';
    exchangeSegment: string;
    productType: string;
    buyAvg: number;
    sellAvg: number;
    costPrice: number;
    buyQty: number;
    sellQty: number;
    netQty: number;
    realizedProfit: number;
    unrealizedProfit: number;
    multiplier: number;
    carryForwardBuyQty: number;
    carryForwardSellQty: number;
    carryForwardBuyValue: number;
    carryForwardSellValue: number;
    dayBuyQty: number;
    daySellQty: number;
    dayBuyValue: number;
    daySellValue: number;
    drvExpiryDate: string;
    drvOptionType: 'CALL' | 'PUT';
    drvStrikePrice: number;
    crossCurrency: boolean;
}; 